/*
 * Copyright (c) 2004-2014, Willem Cazander
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided
 * that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this list of conditions and the
 *   following disclaimer.
 * * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and
 *   the following disclaimer in the documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
 * THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
 * OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
 * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package org.x4o.xml.eld.xsd;

import java.io.File;
import java.util.HashMap;
import java.util.Map;

import org.x4o.xml.X4ODriver;
import org.x4o.xml.X4ODriverManager;
import org.x4o.xml.eld.CelDriver;
import org.x4o.xml.eld.EldDriver;
import org.x4o.xml.eld.EldModuleLoaderCore;
import org.x4o.xml.eld.xsd.EldXsdLanguageTask;
import org.x4o.xml.io.X4OWriterTest;
import org.x4o.xml.io.sax.ext.ContentWriterXml;
import org.x4o.xml.io.sax.ext.PropertyConfig;
import org.x4o.xml.lang.task.X4OLanguageTask;
import org.x4o.xml.test.swixml.SwiXmlDriver;

import junit.framework.TestCase;

/**
 * Tests some code for eld schema generating
 * 
 * @author Willem Cazander
 * @version 1.0 Auh 16, 2012
 */
public class EldXsdLanguageTaskTest extends TestCase {

	private File createOutputPath(String dir) throws Exception {
		File result = new File("target/tests"+File.separator+dir);
		if (result.exists()==false) {
			result.mkdirs();
		}
		return result;
	}
	
	private File testSchema(String language,String outputPostfix,Map<String,Object> props) throws Exception {
		X4ODriver<?> driver = X4ODriverManager.getX4ODriver(language);
		X4OLanguageTask task = driver.getLanguageTask(EldXsdLanguageTask.TASK_ID);
		PropertyConfig config = task.createTaskConfig();
		File outputPath  = createOutputPath(outputPostfix);
		config.setProperty(EldXsdWriter.OUTPUT_PATH,outputPath);
		config.setProperty(EldXsdWriter.OUTPUT_DOCUMENTATION,false);
		config.setProperty(ContentWriterXml.PROLOG_LICENCE_FILE,new File("../license.txt"));
		config.setProperty(ContentWriterXml.PROLOG_USER_COMMENT,"Generated by junit-test-run in class: "+this.getClass().getSimpleName());
		if (props!=null) {
			for (String key:props.keySet()) {
				Object value = props.get(key);
				config.setProperty(key, value);
			}
		}
		task.createTaskExecutor(config).execute(driver.createLanguage());
		assertTrue(outputPath.exists());
		assertTrue(outputPath.list()!=null);
		return outputPath;
	}
	
	public void testEldSchema() throws Exception {
		File outputPath = testSchema(EldDriver.LANGUAGE_NAME,"junit-xsd-eld",null);
		assertTrue(outputPath.list().length>2);
	}
	
	public void testEldCoreSchema() throws Exception {
		File outputPath = testSchema(CelDriver.LANGUAGE_NAME,"junit-xsd-cel",null);
		assertTrue(outputPath.list().length>1);
	}
	
	public void testSwiXmlSchema() throws Exception {
		File outputPath = testSchema(SwiXmlDriver.LANGUAGE_NAME,"junit-xsd-swixml",null);
		assertTrue(outputPath.list().length>1);
	}
	
	public void testFilterNamespace() throws Exception {
		Map<String,Object> props = new HashMap<String,Object>();
		props.put(EldXsdWriter.FILTER_NAMESPACE, EldModuleLoaderCore.CEL_ROOT_URI);
		File outputPath = testSchema(CelDriver.LANGUAGE_NAME,"junit-one-ns",props);
		assertTrue(outputPath.list().length==1);
	}
	
	public void testFilterElement() throws Exception {
		Map<String,Object> props = new HashMap<String,Object>();
		props.put(EldXsdWriter.FILTER_NAMESPACE, EldModuleLoaderCore.CEL_CORE_URI);
		props.put(EldXsdWriter.FILTER_ELEMENT, "elementInterface");
		props.put(EldXsdWriter.PROLOG_GENERATED_BY_ENABLE, false);
		props.put(EldXsdWriter.PROLOG_PROVIDER_INFO_ENABLE, false);
		props.put(ContentWriterXml.PROLOG_LICENCE_ENABLE,false);
		File outputPath = testSchema(CelDriver.LANGUAGE_NAME,"junit-one-element",props);
		assertTrue(outputPath.list().length==1);
		
		String text = X4OWriterTest.readFile(new File("target/tests/junit-one-element/cel-core-1.0.xsd"));
		assertNotNull(text);
		assertTrue(text.contains("elementInterface"));
		assertFalse(text.contains("module"));
		assertFalse(text.contains("attributeAlias"));
		assertFalse(text.contains("bindingHandler"));
		assertFalse(text.contains("classConverter"));
		
		assertTrue(text.length()<10000);
	}
}
